// Generated by https://quicktype.io

export interface NewProjectInterface {
    name:               string;
    description:        string;
    state:              string;
    group:              string;
    number_of_students: number;
}
