// Generated by https://quicktype.io

export interface NewProjectInterface {
    name:               string;
    description:        string;
    state:              string;
    numberOfStudents:   number;
    grupo:              Group;
    registeredPersons:  number;
    full:               boolean;
    semestre:           number;
    fecha_inicio:       string;
    fecha_finalizacion: string;
}

interface Group {
    id: string;
}
