// Generated by https://quicktype.io

export interface PersonWithProject {
    status:    number;
    statusMsg: string;
    data:      PersonProject[];
}

export interface PersonProject {
    id:         string;
    created_at: string;
    updated_at: string;
    state:      boolean;
    person:     Person;
}

export interface Person {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    institutional_mail: string;
    names:              string;
    lastnames:          string;
    code:               string;
    num_document:       string;
    img:                string;
    active:             boolean;
}
