// // Generated by https://quicktype.io

// export interface GroupSubjectInterface {
//     status:    number;
//     statusMsg: string;
//     data:      Data;
// }

// export interface Data {
//     id:    string;
//     name:  string;
//     code:  string;
//     group: Group[];
// }

// export interface Group {
//     id:   string;
//     name: string;
// }


// Generated by https://quicktype.io

export interface GroupSubjectInterface {
    status:    number;
    statusMsg: string;
    data:      SubjectData;
}

export interface SubjectData {
    id:    string;
    name:  string;
    code:  string;
    group: GroupData[];
}

export interface GroupData {
    id:      string;
    name:    string;
    persons: PersonElement[];
}

export interface PersonElement {
    id:     string;
    person: PersonPerson;
}

export interface PersonPerson {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    institutional_mail: string;
    names:              string;
    lastnames:          string;
    code:               string;
    num_document:       string;
    img:                null;
    active:             boolean;
}
