// Generated by https://quicktype.io

export interface GroupSubjectInterface {
    status:    number;
    statusMsg: string;
    data:      Data;
}

export interface Data {
    id:    string;
    name:  string;
    code:  string;
    group: Group[];
}

export interface Group {
    id:   string;
    name: string;
}
