// Generated by https://quicktype.io

export interface NewGroupInterface {
    status:    number;
    statusMsg: string;
    data:      Data;
}

export interface Data {
    name:       string;
    subject:    Subject;
    id:         string;
    created_at: string;
    updated_at: string;
    active:     boolean;
}

export interface Subject {
    id:         string;
    created_at: string;
    updated_at: string;
    name:       string;
    code:       string;
}
