// Generated by https://quicktype.io

export interface RegisterPerson {
    names:              string;
    lastnames:          string;
    institutional_mail: string;
    password:           string;
    code:               string;
    role_id:            string;
    document_id:        string;
}
