// Generated by https://quicktype.io

export interface AllPersonGroupInterface {
    status:    number;
    statusMsg: string;
    data:      DatumPerson[];
}

export interface DatumPerson {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    institutional_mail: string;
    names:              string;
    lastnames:          string;
    code:               string;
    num_document:       string;
    img:                null;
    active:             boolean;
    groups:             Group[];
    role:               Role;
}

export interface Group {
    id:         string;
    created_at: string;
    updated_at: string;
    state:      string;
    active:     boolean;
}

export interface Role {
    name: string;
}
