// Generated by https://quicktype.io

export interface GroupProjectsInterface {
    status:    number;
    statusMsg: string;
    data:      Data;
}

export interface Data {
    name:    string;
    active:  boolean;
    project: ProjectInterface[];
}

export interface ProjectInterface {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    name:               string;
    description:        string;
    active:             boolean;
    state:              string;
    number_of_students: number;
    full:               boolean;
}
