export interface ResponseHttp {
    status: number,
    statusMsg: string,
    data: string
}

// Generated by https://quicktype.io

export interface ResponseToken {
    status:    number;
    statusMsg: string;
    data:      Data;
}

export interface Data {
    accessToken: string;
}
