// Generated by https://quicktype.io

export interface AllTasksOfProjectInterface {
    status:    number;
    statusMsg: string;
    data:      TasksInterface[];
}

export interface TasksInterface {
    id:           string;
    created_at:   string;
    updated_at:   string;
    name:         string;
    description:  string;
    expired_date: string;
    project:      Project[];
}

export interface Project {
    id:           string;
    created_at:   string;
    updated_at:   string;
    expired_date: string;
    state:        string;
}
