// Generated by https://quicktype.io

export interface NewTaskInterface {
    name:         string;
    description:  string;
    expired_date: string;
    group:        string;
    expired:      boolean
}
