// Generated by https://quicktype.io

export interface TaskOfGroupInterface {
    status:    number;
    statusMsg: string;
    data:      ListTaskGroup[];
}

export interface ListTaskGroup {
    id:           string;
    created_at:   string;
    updated_at:   string;
    name:         string;
    description:  string;
    expired_date: string;
}
