// Generated by https://quicktype.io

export interface ViewTaskInterface {
    status:    number;
    statusMsg: string;
    data:      taskInterface;
}

export interface taskInterface {
    id:           string;
    created_at:   string;
    updated_at:   string;
    name:         string;
    description:  string;
    expired_date: string;
    active:       boolean;
    group:        Group;
}

export interface Group {
    name:    string;
    subject: Subject;
}

export interface Subject {
    name: string;
    code: string;
}
