// Generated by https://quicktype.io

export interface ViewMyProjects {
    status:    number;
    statusMsg: string;
    data:      Data;
}

export interface Data {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    institutional_mail: string;
    names:              string;
    lastnames:          string;
    code:               string;
    num_document:       string;
    img:                string;
    active:             boolean;
    projects:           ListMyProjects[];
}

export interface ListMyProjects {
    id:         string;
    created_at: string;
    updated_at: string;
    state:      boolean;
    project:    ProjectProject;
}

export interface ProjectProject {
    id:                 string;
    created_at:         string;
    updated_at:         string;
    name:               string;
    description:        string;
    active:             boolean;
    state:              string;
    number_of_students: number;
    registered_persons:  number;
    full:               boolean;
    group:              Group;
}

export interface Group {
    id:         string;
    created_at: string;
    updated_at: string;
    name:       string;
    active:     boolean;
    subject:    Subject;
}

export interface Subject {
    id:         string;
    created_at: string;
    updated_at: string;
    name:       string;
    code:       string;
}
