// Generated by https://quicktype.io

export interface MySubjectInterface {
    status: number;
    statusMsg: string;
    data: MySubjectsData;
}

export interface MySubjectsData {
    names: string;
    id: string
    groups: GroupElement[];
}

export interface GroupElement {
    state: string;
    group: GroupGroup;
}

export interface GroupGroup {
    name: string;
    subject: Subject;
    id: string,
    active: boolean,
}

export interface Subject {
    name: string;
    code: string;
}
