// Generated by https://quicktype.io

export interface SubjectInterface {
    status:    number;
    statusMsg: string;
    data:      SubjectData[];
}

export interface SubjectData {
    id:         string;
    created_at: string;
    updated_at: string;
    name:       string;
    code:       string;
}